### ISSUE TITLE
运行sift.py时报错

### ISSUE THREAD

**Issue by ZHAOSHICHEN94** [o0o0o0o0o0o0o/image-processing-from-scratch#9]
Traceback (most recent call last):
  File "/home/zsc/桌面/image-processing-from-scratch/sift/SIFT.py", line 557, in <module>
    drawLines(X1,X2,Y1,Y2,match[0][:,0],result)
  File "/home/zsc/桌面/image-processing-from-scratch/sift/SIFT.py", line 503, in drawLines
    img = Lines(img,info)
  File "/home/zsc/桌面/image-processing-from-scratch/sift/SIFT.py", line 491, in Lines
    result[i,j] = color
ValueError: cannot copy sequence with size 3 to array axis with dimension 4

**Comment by mudanxiaowu** [comment]
您好，您的邮件已收到，谢谢This is an automatic reply, confirming that your e-mail was received.Thank you.

**Comment by huangxiaohuok** [comment]
文件已经收到，谢谢配合！

**Comment by ZHAOSHICHEN94** [comment]
我的邮箱 1101894683@qq.com
谢谢
